### ISSUE TITLE
Specific network interface

### ISSUE THREAD

**Issue by alexmorbo** [Jamesits/docker-ripe-atlas#1]
Hey!

This container can use specific network interface to access the world?
I mean i have this:
```
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether f0:4d:a2:02:aa:8f brd ff:ff:ff:ff:ff:ff
    inet 185.148.xxx.xxx/26 brd 185.148.aaa.aaa scope global eno1
       valid_lft forever preferred_lft forever
    inet 185.148.xxx.zzz/26 brd 185.148.aaa.aaa scope global secondary eno1:0
       valid_lft forever preferred_lft forever
```

So, I've got 2 white static ips: 185.148.xxx.xxx and 185.148.xxx.zzz, and I want to probe going to world with ip address 185.148.xxx.zzz

How can i do this?

**Comment by Jamesits** [comment]
I've not done it myself, but I'm pretty sure that can be achieved by setting up SNAT rules yourself instead of let Docker install its own default masquerade rules.

First we create a new bridge network with masquerading disabled:
```shell
docker network create \
    -o "com.docker.network.bridge.enable_ip_masquerade"="false" \
    --subnet "192.168.1.0/24" \
    ripe-atlas-network
```

Then manually set up an iptables SNAT rule:

```
iptables -t nat -A POSTROUTING -o eno1 -s 192.168.1.0/24 -j SNAT --to-source 185.148.xxx.zzz
```
(Note: this will not survive a server reboot. Use `iptables-persistent` or something to make it persistent across reboots.)

Finally launch the container with `--net=ripe-atlas-network` argument.

**Comment by alexmorbo** [comment]
@Jamesits great, thanks!

btw, this docker image 100% works?
I still waiting approve with this image from ripe 3 days :(

**Comment by Jamesits** [comment]
The image works most of the time (if it doesn't work, please create a new issue and post the logs), but RIPE Atlas team seems to be denying some requests silently. I requested 5 probes and 3 of them are accepted.

**Comment by alexmorbo** [comment]
Thanks!
